'use strict'

module.exports = [
  { input: '별점 높은 영상 찾아줘', expected: { toolName: 'search_videos', arguments: { sortBy: 'rating' } } },
  { input: '별점 4점 이상만 보여줘', expected: { toolName: 'search_videos', arguments: { minRating: 4 } } },
  { input: '5점 배우 작품 찾아줘', expected: { toolName: 'search_videos', arguments: { actorMinRating: 5 } } },
  { input: '평점 좋은 배우가 나온 영상 중 미복사만', expected: { toolName: 'search_videos', arguments: { onlyNotCopied: true } } },
  { input: '최근 추가한 영상 보여줘', expected: { toolName: 'search_videos', arguments: { sortBy: 'recent' } } },
  { input: '한 번도 안 본 영상 찾아줘', expected: { toolName: 'search_videos', arguments: { } } },
  { input: '복사 안 한 추천작만 골라줘', expected: { toolName: 'search_videos', arguments: { onlyNotCopied: true } } },
  { input: '메타데이터 부족한 배우 찾아줘', expected: { toolName: 'search_actors', arguments: { metadataMissing: true } } },
  { input: '소속사가 없는 배우 보여줘', expected: { toolName: 'search_actors', arguments: { metadataMissing: true } } },
  { input: '태그가 없는 배우만', expected: { toolName: 'search_actors', arguments: { metadataMissing: true } } },
  { input: '별점 높은 배우 찾아줘', expected: { toolName: 'search_actors', arguments: { minRating: 4 } } },
  { input: '영상이 많은 배우 순으로 보여줘', expected: { toolName: 'search_actors', arguments: { } } },
  { input: '드라이브별 용량 알려줘', expected: { toolName: 'get_drive_stats', arguments: { drive: null } } },
  { input: 'D드라이브 영상 몇 개 있어', expected: { toolName: 'get_drive_stats', arguments: { drive: 'D:' } } },
  { input: '어느 드라이브가 제일 많이 차지해', expected: { toolName: 'get_drive_stats', arguments: { drive: null } } },
  { input: '저장소 현황 요약해줘', expected: { toolName: 'get_drive_stats', arguments: { drive: null } } },
  { input: '용량 많이 먹는데 안 본 영상 정리해줘', expected: { toolName: 'get_delete_candidates', arguments: { lowPlayCount: true } } },
  { input: 'D드라이브에서 지워도 될 만한 것 찾아줘', expected: { toolName: 'get_delete_candidates', arguments: { drive: 'D:' } } },
  { input: '복사도 안 했고 별점 낮은 영상 보여줘', expected: { toolName: 'get_delete_candidates', arguments: { onlyNotCopied: true, lowRating: true } } },
  { input: '공간 확보하려면 뭘 먼저 정리해야 해', expected: { toolName: 'get_delete_candidates', arguments: { } } },
  { input: '10기가 넘고 안 본 영상만', expected: { toolName: 'get_delete_candidates', arguments: { lowPlayCount: true, minSizeBytes: 10 * 1024 ** 3 } } },
  { input: '그중에서 미복사만', expected: { toolName: 'search_videos', arguments: { onlyNotCopied: true } } },
  { input: '거기서 별점 3점 이상은 빼줘', expected: { toolName: 'search_videos', arguments: { } } },
  { input: '방금 목록에서 자막 없는 것만', expected: { toolName: 'search_videos_without_subtitles', arguments: { } } },
  { input: '그 배우들 작품만 보여줘', expected: { toolName: 'search_videos', arguments: { } } },
  { input: '그중 10기가 넘는 것만', expected: { toolName: 'search_videos', arguments: { } } },
  { input: '괜찮은 거 보여줘', expected: { needsClarification: true } },
  { input: '정리 좀 해줘', expected: { needsClarification: true } },
  { input: '뭐 볼까', expected: { needsClarification: true } },
  { input: '좋은 거 찾아줘', expected: { needsClarification: true } },
  { input: '자막 없는 영상 몇개인지 알려줘', expected: { toolName: 'get_unmapped_subtitle_summary', arguments: { } } },
  { input: '자막 없는 파일들 정리해서 보여줄래', expected: { toolName: 'search_videos_without_subtitles' } },
  { input: '자막 없는 영상 목록으로 정리해줘', expected: { toolName: 'search_videos_without_subtitles' } },
  { input: '자막 없는 파일을 보기 좋게 정리해서 보여줘', expected: { toolName: 'search_videos_without_subtitles' } },
  { input: '자막 없는 파일 중 지워도 될 것 정리해줘', expected: { toolName: 'get_delete_candidates' } },
  { input: '폴더별 자막 미매핑 개수 보여줘', expected: { toolName: 'get_unmapped_subtitle_summary', arguments: { } } },
  { input: 'D드라이브 자막 미매핑 통계', expected: { toolName: 'get_unmapped_subtitle_summary', arguments: { drive: 'D:' } } },
  { input: '선택한 것만 찾아줘', expected: { toolName: 'search_videos', arguments: { } } },
  { input: '선택한 영상들 중 미복사만', expected: { toolName: 'search_videos', arguments: { onlyNotCopied: true } } },
  { input: '별점 높은 작품 중 아직 복사 안 한 것', expected: { toolName: 'search_videos', arguments: { sortBy: 'rating', onlyNotCopied: true } } },
  { input: '배우 별점 높은 작품 찾아줘', expected: { toolName: 'search_videos', arguments: { actorMinRating: 4 } } },
  { input: 'D드라이브에서 용량 큰 것만', expected: { toolName: 'get_delete_candidates', arguments: { drive: 'D:' } } },
  { input: '현재 화면 기준으로 추천해줘', expected: { toolName: 'search_videos', arguments: { } } },
  { input: '저 목록에서 최근 추가만', expected: { toolName: 'search_videos', arguments: { sortBy: 'recent' } } },
  { input: '그 목록에서 별점 높은 것만', expected: { toolName: 'search_videos', arguments: { sortBy: 'rating' } } },
  { input: '그중에서 자막 없는 것만', expected: { toolName: 'search_videos_without_subtitles', arguments: { } } },
  { input: '배우 메타데이터가 비어 있는 사람만', expected: { toolName: 'search_actors', arguments: { metadataMissing: true } } },
]